version: '3.5'
services:
  catchapp-db:
    image: postgres
    container_name: catchapp_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U postgres
      interval: 5m
      timeout: 10s
      retries: 5

  catchapp-backend:
    build: .
    container_name: catchapp_backend
    restart: unless-stopped
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - catchapp-db
    volumes:
      - ./static:/app/static
      - ./media:/app/media


volumes:
  postgres_data:
