"""alter meetings

Revision ID: 02886d0b0e6b
Revises: 2a91f20d13e6
Create Date: 2023-02-23 01:28:43.158611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02886d0b0e6b'
down_revision = '2a91f20d13e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('user_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('meetings', sa.Column('contact_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('meetings', 'user_two')
    op.drop_column('meetings', 'user_one')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('user_one', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('meetings', sa.Column('user_two', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('meetings', 'contact_data')
    op.drop_column('meetings', 'user_data')
    # ### end Alembic commands ###
