"""meeting slots

Revision ID: 2a91f20d13e6
Revises: c921c164090a
Create Date: 2023-02-22 01:40:20.522124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a91f20d13e6'
down_revision = 'c921c164090a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('slots', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'meetings', ['contacts_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='unique')
    op.drop_column('meetings', 'slots')
    # ### end Alembic commands ###
