"""fcm_token

Revision ID: 0f96a920b659
Revises: 95e7abed2fa0
Create Date: 2023-03-16 21:03:43.538449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f96a920b659'
down_revision = '95e7abed2fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('device', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device')
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###
